# Generated by Django 3.1.3 on 2020-12-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20201210_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
        ),
    ]
